### ISSUE TITLE
Multiple MCRE commands blow up

### ISSUE THREAD

**Issue by miklosduma** [ethertricity/bluesky#12]
If you run the `MCRE n` command - which creates n random aircrafts - twice or thrice, the simulation freezes with the following error message:

```python
Traceback (most recent call last):
  File "BlueSky_qtgl.py", line 80, in <module>
    MainLoop()
  File "BlueSky_qtgl.py", line 38, in MainLoop
    manager.run()
  File "/Users/miklosduma/Projects/bluesky/bluesky/sim/qtgl/nodemanager.py", line 28, in run
    bs.sim.doWork()
  File "/Users/miklosduma/Projects/bluesky/bluesky/sim/qtgl/simulation.py", line 98, in doWork
    stack.process()
  File "/Users/miklosduma/Projects/bluesky/bluesky/stack/stack.py", line 1196, in process
    results = function(*arglist)  # * = unpack list to call arguments
  File "/Users/miklosduma/Projects/bluesky/bluesky/traf/traffic.py", line 256, in mcreate
    self.create_children(n)
  File "/Users/miklosduma/Projects/bluesky/bluesky/tools/trafficarrays.py", line 97, in create_children
    child.create(n)
  File "/Users/miklosduma/Projects/bluesky/bluesky/traf/activewpdata.py", line 23, in create
    super(ActiveWaypoint, self).create(n)
  File "/Users/miklosduma/Projects/bluesky/bluesky/tools/trafficarrays.py", line 81, in create
    fulltype = str(self.Vars[v].dtype)
AttributeError: 'float' object has no attribute 'dtype'
# Sometimes it says 'list' object has no attribute 'dtype'
```

**Comment by jooste** [comment]
Hi, this should be fixed (in the main version) in 6af8ead and aa1029a.

**Comment by reube** [comment]
Will validate by writing test and then close.
